export const programsListActionTypes = {
	// create
	CREATING_REMOTE_PROGRAMS_LIST: "CREATING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_CREATED: "REMOTE_PROGRAMS_LIST_CREATED",

	// update
	UPDATE_LOCAL_PROGRAMS_LIST: "UPDATE_LOCAL_PROGRAMS_LIST",
	UPDATING_REMOTE_PROGRAMS_LIST: "UPDATING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_UPDATED: "REMOTE_PROGRAMS_LIST_UPDATED",

	// sync
	SYNCING_PROGRAMS_LIST: "SYNCING_PROGRAMS_LIST",
	PROGRAMS_LIST_UP_TO_DATE: "PROGRAMS_LIST_UP_TO_DATE",
	PROGRAMS_LIST_SYNCED: "PROGRAMS_LIST_SYNCED",

	// remove
	CLEAR_LOCAL_PROGRAMS_LIST: "CLEAR_LOCAL_PROGRAMS_LIST",
	REMOVING_REMOTE_PROGRAMS_LIST: "REMOVING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_REMOVED: "REMOTE_PROGRAMS_LIST_REMOVED",
};
