export const programsListActionTypes = {
	// create remote
	CREATING_REMOTE_PROGRAMS_LIST: "CREATING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_CREATED: "REMOTE_PROGRAMS_LIST_CREATED",
	CREATE_REMOTE_PROGRAMS_LIST_FAIL: "CREATE_REMOTE_PROGRAMS_LIST_FAIL",

	// update remote
	UPDATING_REMOTE_PROGRAMS_LIST: "UPDATING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_UPDATED: "REMOTE_PROGRAMS_LIST_UPDATED",
	UPDATE_REMOTE_PROGRAMS_LIST_FAIL: "UPDATE_REMOTE_PROGRAMS_LIST_FAIL",

	// sync
	SYNCING_PROGRAMS_LIST: "SYNCING_PROGRAMS_LIST",
	PROGRAMS_LIST_UP_TO_DATE: "PROGRAMS_LIST_UP_TO_DATE",
	PROGRAMS_LIST_SYNCED: "PROGRAMS_LIST_SYNCED",
	SYNC_PROGRAMS_LIST_FAIL: "SYNC_PROGRAMS_LIST_FAIL",

	// remove remote
	REMOVING_REMOTE_PROGRAMS_LIST: "REMOVING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_REMOVED: "REMOTE_PROGRAMS_LIST_REMOVED",
	REMOVE_REMOTE_PROGRAMS_LIST_FAIL: "REMOVE_REMOTE_PROGRAMS_LIST_FAIL",

	// update local
	UPDATE_LOCAL_PROGRAMS_LIST: "UPDATE_LOCAL_PROGRAMS_LIST",
	CLEAR_LOCAL_PROGRAMS_LIST: "CLEAR_LOCAL_PROGRAMS_LIST",
};
