export const programActionTypes = {
	// Create remote
	CREATING_REMOTE_PROGRAM: "CREATING_REMOTE_PROGRAM",
	REMOTE_PROGRAM_CREATED: "REMOTE_PROGRAM_CREATED",
	REMOTE_PROGRAM_CREATE_FAIL: "REMOTE_PROGRAM_CREATE_FAIL",

	// Update remote
	UPDATING_REMOTE_CURRENT_PROGRAM: "UPDATING_REMOTE_CURRENT_PROGRAM",
	REMOTE_CURRENT_PROGRAM_UPDATED: "REMOTE_CURRENT_PROGRAM_UPDATED",
	REMOTE_CURRENT_PROGRAM_UPDATE_FAIL: "REMOTE_CURRENT_PROGRAM_UPDATE_FAIL",

	// Publish
	PUBLISHING_CURRENT_PROGRAM: "PUBLISHING_CURRENT_PROGRAM",
	CURRENT_PROGRAM_PUBLISHED: "CURRENT_PROGRAM_PUBLISHED",
	CURRENT_PROGRAM_PUBLISH_FAIL: "CURRENT_PROGRAM_PUBLISH_FAIL",

	// Update
	UPDATE_LOCAL_CURRENT_PROGRAM: "UPDATE_LOCAL_CURRENT_PROGRAM",
	UPDATE_MAX_CUSTOM_REST: "UPDATE_MAX_CUSTOM_REST",
	LOAD_PROGRAM: "LOAD_PROGRAM",
	LOAD_STANDARD_PROGRAM: "LOAD_STANDARD_PROGRAM",
	CLEAR_LOCAL_CURRENT_PROGRAM: "CLEAR_LOCAL_CURRENT_PROGRAM",
};
