const programActionTypes = {
	GET_FIELDS: "GET_FIELDS",
	UPDATE_MAX_CUSTOM_REST: "UPDATE_MAX_CUSTOM_REST",
	UPDATE_LOCAL_PROGRAM: "UPDATE_LOCAL_PROGRAM",
	CREATING_REMOTE_PROGRAM: "CREATING_REMOTE_PROGRAM",
	UPDATING_REMOTE_PROGRAM: "UPDATING_REMOTE_PROGRAM",
	SYNCING_PROGRAM: "SYNCING_PROGRAM",
	REMOTE_PROGRAM_CREATED: "REMOTE_PROGRAM_CREATED",
	REMOTE_PROGRAM_UPDATED: "REMOTE_PROGRAM_UPDATED",
	PROGRAM_UP_TO_DATE: "PROGRAM_UP_TO_DATE",
	PROGRAM_SYNCED: "PROGRAM_SYNCED",
	CLEAR_LOCAL_PROGRAM: "CLEAR_LOCAL_PROGRAM",
	PUBLISHING_PROGRAM: "PUBLISHING_PROGRAM",
	PROGRAM_PUBLISHED: "PROGRAM_PUBLISHED",
	PROGRAM_PUBLISH_FAIL: "PROGRAM_PUBLISH_FAIL",
	LOAD_PROGRAM: "LOAD_PROGRAM",
};

export default programActionTypes;
