export const programsActionTypes = {
	// ------------------ Remote Collection -------------------------

	// Download remote collection
	DOWNLOADING_PROGRAMS: "DOWNLOADING_PROGRAMS",
	PROGRAMS_DOWNLADED: "PROGRAMS_DOWNLADED",
	PROGRAMS_DOWNLAD_FAIL: "PROGRAMS_DOWNLAD_FAIL",
	PROGRAMS_UP_TO_DATE: "PROGRAMS_UP_TO_DATE",

	// Remove remote programs/collection
	REMOVING_ALL_REMOTE_PRIVATE_PROGRAMS: "REMOVING_ALL_REMOTE_PRIVATE_PROGRAMS",
	ALL_REMOTE_PRIVATE_PROGRAMS_REMOVED: "ALL_REMOTE_PRIVATE_PROGRAMS_REMOVED",

	// ------------------ Local Collection -------------------------

	// Modify local collection
	REPLACE_COLLECTION: "REPLACE_COLLECTION",
	ADD_LOCAL_SAVED_PROGRAM: "ADD_LOCAL_SAVED_PROGRAM",
	REMOVE_LOCAL_SAVED_PROGRAM: "REMOVE_LOCAL_SAVED_PROGRAM",
	SET_CURRENT_PROGRAM: "SET_CURRENT_PROGRAM",
	SET_CURRENT_STANDARD_PROGRAM: "SET_CURRENT_STANDARD_PROGRAM",
	SET_EDITED_PROGRAM: "SET_EDITED_PROGRAM",

	// Remove local collection
	CLEAR_LOCAL_PROGRAMS_GROUP: "CLEAR_LOCAL_PROGRAMS_GROUP",
	CLEAR_LOCAL_PROGRAMS: "CLEAR_LOCAL_PROGRAMS",

	// --------------- Remote individual program ----------------------

	// Create remote
	CREATING_REMOTE_PROGRAM: "CREATING_REMOTE_PROGRAM",
	REMOTE_PROGRAM_CREATED: "REMOTE_PROGRAM_CREATED",
	REMOTE_PROGRAM_CREATE_FAIL: "REMOTE_PROGRAM_CREATE_FAIL",

	// Update remote
	UPDATING_REMOTE_PROGRAM: "UPDATING_REMOTE_PROGRAM",
	REMOTE_PROGRAM_UPDATED: "REMOTE_PROGRAM_UPDATED",
	REMOTE_PROGRAM_UPDATE_FAIL: "REMOTE_PROGRAM_UPDATE_FAIL",

	// Remove remote
	REMOVING_REMOTE_PROGRAM: "REMOVING_REMOTE_PROGRAM",
	REMOTE_PROGRAM_REMOVED: "REMOTE_PROGRAM_REMOVED",

	// --------------- Local individual program ----------------------

	// Publish
	PUBLISHING_PROGRAM: "PUBLISHING_PROGRAM",
	PROGRAM_PUBLISHED: "PROGRAM_PUBLISHED",
	PROGRAM_PUBLISH_FAIL: "PROGRAM_PUBLISH_FAIL",

	// Modify
	MODIFY_LOCAL_SAVED_PROGRAM: "MODIFY_LOCAL_SAVED_PROGRAM",
	MODIFY_MAX_CUSTOM_REST: "MODIFY_MAX_CUSTOM_REST",
};
