export const userActionTypes = {
	USER_LOADING: "USER_LOADING",
	USER_LOADED: "USER_LOADED",
	LOAD_USER_FAIL: "LOAD_USER_FAIL",
	AUTH_SUCCESS: "AUTH_SUCCESS",
	SKIP_AUTH: "SKIP_AUTH",
	CLEAR_USER_DATA: "CLEAR_USER_DATA",
};
