export const programsListActionTypes = {
	// create remote
	CREATING_REMOTE_PROGRAMS_LIST: "CREATING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_CREATED: "REMOTE_PROGRAMS_LIST_CREATED",
	CREATE_REMOTE_PROGRAMS_LIST_FAIL: "CREATE_REMOTE_PROGRAMS_LIST_FAIL",

	// update remote
	UPDATING_REMOTE_PROGRAMS_LIST: "UPDATING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_UPDATED: "REMOTE_PROGRAMS_LIST_UPDATED",
	UPDATE_REMOTE_PROGRAMS_LIST_FAIL: "UPDATE_REMOTE_PROGRAMS_LIST_FAIL",

	// remove remote
	REMOVING_REMOTE_PROGRAMS_LIST: "REMOVING_REMOTE_PROGRAMS_LIST",
	REMOTE_PROGRAMS_LIST_REMOVED: "REMOTE_PROGRAMS_LIST_REMOVED",
	REMOVE_REMOTE_PROGRAMS_LIST_FAIL: "REMOVE_REMOTE_PROGRAMS_LIST_FAIL",

	// update local
	MODIFY_LOCAL_SAVED_PROGRAMS_LIST: "MODIFY_LOCAL_SAVED_PROGRAMS_LIST",
	CLEAR_LOCAL_PROGRAMS_LIST: "CLEAR_LOCAL_PROGRAMS_LIST",
};
