export const programsActionTypes = {
	// multiple
	DOWNLOADING_PROGRAMS: "DOWNLOADING_PROGRAMS",
	PROGRAMS_DOWNLAD_SUCCESS: "PROGRAMS_DOWNLAD_SUCCESS",
	PROGRAMS_DOWNLAD_FAIL: "PROGRAMS_DOWNLAD_FAIL",
	REMOVING_ALL_REMOTE_PROGRAMS: "REMOVING_ALL_REMOTE_PROGRAMS",
	ALL_REMOTE_PROGRAMS_REMOVED: "ALL_REMOTE_PROGRAMS_REMOVED",
	CLEAR_LOCAL_PROGRAMS: "CLEAR_LOCAL_PROGRAMS",

	// single
	ADD_PRIVATE_PROGRAM: "ADD_PRIVATE_PROGRAM",
	REMOVE_LOCAL_PRIVATE_PROGRAM: "REMOVE_LOCAL_PRIVATE_PROGRAM",
	REMOVING_REMOTE_PROGRAM: "REMOVING_REMOTE_PROGRAM",
	REMOTE_PROGRAM_REMOVED: "REMOTE_PROGRAM_REMOVED",
	UPDATING_REMOTE_PUBLIC_PROGRAM: "UPDATING_REMOTE_PUBLIC_PROGRAM",
	REMOTE_PUBLIC_PROGRAM_UPDATED: "REMOTE_PUBLIC_PROGRAM_UPDATED",
};
