export const programsActionTypes = {
	DOWNLOADING_PROGRAMS: "DOWNLOADING_PROGRAMS",
	PROGRAMS_DOWNLAD_SUCCESS: "PROGRAMS_DOWNLAD_SUCCESS",
	PROGRAMS_DOWNLAD_FAIL: "PROGRAMS_DOWNLAD_FAIL",
	ADD_PRIVATE_PROGRAM: "ADD_PRIVATE_PROGRAM",
	REMOVE_PRIVATE_PROGRAM: "REMOVE_PRIVATE_PROGRAM",
};
