export const programsActionTypes = {
	// multiple
	DOWNLOADING_PROGRAMS: "DOWNLOADING_PROGRAMS",
	PROGRAMS_DOWNLADED: "PROGRAMS_DOWNLADED",
	PROGRAMS_DOWNLAD_FAIL: "PROGRAMS_DOWNLAD_FAIL",
	REMOVING_ALL_REMOTE_PRIVATE_PROGRAMS: "REMOVING_ALL_REMOTE_PRIVATE_PROGRAMS",
	ALL_REMOTE_PRIVATE_PROGRAMS_REMOVED: "ALL_REMOTE_PRIVATE_PROGRAMS_REMOVED",
	CLEAR_LOCAL_PROGRAMS: "CLEAR_LOCAL_PROGRAMS",

	// single
	ADD_SAVED_PROGRAM: "ADD_SAVED_PROGRAM",
	REMOVE_LOCAL_SAVED_PROGRAM: "REMOVE_LOCAL_SAVED_PROGRAM",
	REMOVING_REMOTE_PROGRAM: "REMOVING_REMOTE_PROGRAM",
	REMOTE_PROGRAM_REMOVED: "REMOTE_PROGRAM_REMOVED",
	UPDATING_REMOTE_PUBLIC_PROGRAM: "UPDATING_REMOTE_PUBLIC_PROGRAM",
	REMOTE_PUBLIC_PROGRAM_UPDATED: "REMOTE_PUBLIC_PROGRAM_UPDATED",
};
