const userActionTypes = {
	USER_LOADING: "USER_LOADING",
	USER_LOADED: "USER_LOADED",
	AUTH_SUCCESS: "AUTH_SUCCESS",
	AUTH_ERROR: "AUTH_ERROR",
	SKIP_AUTH: "SKIP_AUTH",
	CLEAR_USER_DATA: "CLEAR_USER_DATA",
};

export default userActionTypes;
