const userActionTypes = {
	USER_LOADING: "USER_LOADING",
	USER_LOADED: "USER_LOADED",
	AUTH_SUCCESS: "AUTH_SUCCESS",
	AUTH_ERROR: "AUTH_ERROR",
	SKIP_AUTH: "SKIP_AUTH",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export default userActionTypes;
