const protocolActionTypes = {
	GET_FIELDS: "GET_FIELDS",
	UPDATE_MAX_CUSTOM_REST: "UPDATE_MAX_CUSTOM_REST",
	UPDATE_LOCAL_PROTOCOL: "UPDATE_LOCAL_PROTOCOL",
	CREATING_REMOTE_PROTOCOL: "CREATING_REMOTE_PROTOCOL",
	UPDATING_REMOTE_PROTOCOL: "UPDATING_REMOTE_PROTOCOL",
	SYNCING_PROTOCOL: "SYNCING_PROTOCOL",
	REMOTE_PROTOCOL_CREATED: "REMOTE_PROTOCOL_CREATED",
	REMOTE_PROTOCOL_UPDATED: "REMOTE_PROTOCOL_UPDATED",
	PROTOCOL_UP_TO_DATE: "PROTOCOL_UP_TO_DATE",
	PROTOCOL_SYNCED: "PROTOCOL_SYNCED",
	CLEAR_LOCAL_PROTOCOL: "CLEAR_LOCAL_PROTOCOL",
};

export default protocolActionTypes;
